### ISSUE TITLE
Show PI on user management page

### ISSUE THREAD

**Issue by umass-jgriffin** [UnityHPC/account-portal#54]
Right now PI's and users are managed on separate pages.  It would be nice if the user management page had a way of indicating what PI group(s) a user is a member of.

**Comment by hakasapl** [comment]
Duplicate of https://github.com/UnityHPC/unity-web-portal/issues/29, which has since closed and will be included in the next release (this Friday hopefully!)

**Comment by umass-jgriffin** [comment]
Ah, that's why I didn't see it already! Thanks!
